"""agent-layer — Make web apps AI-agent-friendly."""

from agent_layer.errors import AgentError, format_error, not_found_error, rate_limit_error
from agent_layer.rate_limit import MemoryStore, create_rate_limiter
from agent_layer.llms_txt import generate_llms_txt, generate_llms_full_txt
from agent_layer.discovery import generate_ai_manifest, generate_json_ld
from agent_layer.a2a import (
    A2AAgentCard,
    A2AConfig,
    A2ASkill,
    generate_agent_card,
    validate_agent_card,
)
from agent_layer.agent_identity import (
    AgentAuthzPolicyRuntime,
    AgentIdentityClaims,
    AgentIdentityConfig,
    AuthzContext,
    AuthzResult,
    SpiffeId,
    TokenValidationError,
    build_audit_event,
    decode_jwt_claims,
    evaluate_authz,
    extract_claims,
    is_spiffe_trusted,
    parse_spiffe_id,
    validate_claims,
)
from agent_layer.analytics import (
    AgentEvent,
    AnalyticsConfig,
    AnalyticsInstance,
    EventBuffer,
    create_analytics,
    detect_agent,
)
from agent_layer.mcp import (
    JsonRpcRequest,
    JsonRpcResponse,
    McpServerConfig,
    McpServerInfo,
    McpToolDefinition,
    build_input_schema,
    format_tool_name,
    generate_server_info,
    generate_tool_definitions,
    handle_json_rpc,
    parse_tool_name,
)

__all__ = [
    "AgentError",
    "format_error",
    "not_found_error",
    "rate_limit_error",
    "MemoryStore",
    "create_rate_limiter",
    "generate_llms_txt",
    "generate_llms_full_txt",
    "generate_ai_manifest",
    "generate_json_ld",
    "AgentEvent",
    "AnalyticsConfig",
    "AnalyticsInstance",
    "EventBuffer",
    "create_analytics",
    "detect_agent",
    "AgentAuthzPolicyRuntime",
    "AgentIdentityClaims",
    "AgentIdentityConfig",
    "AuthzContext",
    "AuthzResult",
    "SpiffeId",
    "TokenValidationError",
    "build_audit_event",
    "decode_jwt_claims",
    "evaluate_authz",
    "extract_claims",
    "is_spiffe_trusted",
    "parse_spiffe_id",
    "validate_claims",
    "A2AAgentCard",
    "A2AConfig",
    "A2ASkill",
    "generate_agent_card",
    "validate_agent_card",
    "JsonRpcRequest",
    "JsonRpcResponse",
    "McpServerConfig",
    "McpServerInfo",
    "McpToolDefinition",
    "build_input_schema",
    "format_tool_name",
    "generate_server_info",
    "generate_tool_definitions",
    "handle_json_rpc",
    "parse_tool_name",
]
