"""agent-layer — Python middleware to make your web app AI-agent-friendly."""

from agent_layer.core.agents_txt import (
    AgentsTxtConfig,
    AgentsTxtRule,
    generate_agents_txt,
    is_agent_allowed,
    parse_agents_txt,
)
from agent_layer.core.a2a import (
    A2AAgentCard,
    A2AAuthScheme,
    A2ACapabilities,
    A2AConfig,
    A2AProvider,
    A2ASkill,
    generate_agent_card,
    validate_agent_card,
)
from agent_layer.core.discovery import (
    AIManifest,
    AIManifestAuth,
    DiscoveryConfig,
    generate_ai_manifest,
    generate_json_ld,
)
from agent_layer.core.errors import (
    AgentError,
    AgentErrorEnvelope,
    AgentErrorOptions,
    format_error,
    not_found_error,
    rate_limit_error,
)
from agent_layer.core.llms_txt import (
    LlmsTxtConfig,
    LlmsTxtSection,
    RouteMetadata,
    RouteParameter,
    generate_llms_txt,
    generate_llms_full_txt,
)
from agent_layer.core.rate_limit import (
    MemoryStore,
    RateLimitConfig,
    RateLimitResult,
    create_rate_limiter,
)
from agent_layer.core.mcp import (
    McpServerConfig,
    McpServerInfo,
    McpToolDefinition,
    format_tool_name,
    build_input_schema,
    generate_tool_definitions,
    generate_server_info,
    parse_tool_name,
    handle_json_rpc,
)
from agent_layer.core.analytics import (
    AgentEvent,
    AnalyticsConfig,
    EventBuffer,
    create_analytics,
    detect_agent,
)
from agent_layer.core.api_keys import (
    ApiKeyConfig,
    CreateApiKeyOptions,
    CreateApiKeyResult,
    ApiKeyValidationResult,
    MemoryApiKeyStore,
    ScopedApiKey,
    create_api_key,
    validate_api_key,
    has_scope,
)
from agent_layer.core.x402 import (
    X402Config,
    X402RouteConfig,
    PaymentRequirements,
    resolve_price,
    build_requirements,
    build_payment_required,
    encode_payment_required,
    decode_payment_payload,
    match_route,
    handle_x402,
)
from agent_layer.core.agent_identity import (
    AgentAuthzPolicy,
    AgentIdentityAuditEvent,
    AgentIdentityClaims,
    AgentIdentityConfig,
    AuthzContext,
    AuthzResult,
    SpiffeId,
    build_audit_event,
    decode_jwt_claims,
    evaluate_authz,
    extract_claims,
    handle_optional_identity,
    handle_require_identity,
    is_spiffe_trusted,
    parse_spiffe_id,
    validate_claims,
)
from agent_layer.core.unified_discovery import (
    DiscoveryFormats,
    UnifiedAuthConfig,
    UnifiedDiscoveryConfig,
    UnifiedSkill,
    generate_all_discovery,
    generate_unified_agents_txt,
    generate_unified_agent_card,
    generate_unified_ai_manifest,
    generate_unified_llms_full_txt,
    generate_unified_llms_txt,
)
from agent_layer.core.ag_ui import (
    AG_UI_HEADERS,
    AgUiEmitter,
    AgUiEventType,
    create_ag_ui_emitter,
    encode_event,
    encode_events,
)
from agent_layer.core.oauth2 import (
    OAuth2Config,
    OAuth2MiddlewareConfig,
    OAuth2TokenError,
    PKCEPair,
    TokenResponse,
    TokenValidationResult,
    build_authorization_url,
    build_oauth2_metadata,
    compute_code_challenge,
    extract_bearer_token,
    generate_code_verifier,
    generate_pkce,
    handle_oauth2,
    validate_access_token,
)
from agent_layer.core.agent_meta import (
    AgentMetaConfig,
    transform_html,
)

__all__ = [
    # agents.txt
    "AgentsTxtConfig",
    "AgentsTxtRule",
    "generate_agents_txt",
    "parse_agents_txt",
    "is_agent_allowed",
    # A2A
    "A2AAgentCard",
    "A2AAuthScheme",
    "A2ACapabilities",
    "A2AConfig",
    "A2AProvider",
    "A2ASkill",
    "generate_agent_card",
    "validate_agent_card",
    # Discovery
    "AIManifest",
    "AIManifestAuth",
    "DiscoveryConfig",
    "generate_ai_manifest",
    "generate_json_ld",
    # Errors
    "AgentError",
    "AgentErrorEnvelope",
    "AgentErrorOptions",
    "format_error",
    "not_found_error",
    "rate_limit_error",
    # LLMs.txt
    "LlmsTxtConfig",
    "LlmsTxtSection",
    "RouteMetadata",
    "RouteParameter",
    "generate_llms_txt",
    "generate_llms_full_txt",
    # Rate limit
    "MemoryStore",
    "RateLimitConfig",
    "RateLimitResult",
    "create_rate_limiter",
    # MCP
    "McpServerConfig",
    "McpServerInfo",
    "McpToolDefinition",
    "format_tool_name",
    "build_input_schema",
    "generate_tool_definitions",
    "generate_server_info",
    "parse_tool_name",
    "handle_json_rpc",
    # Analytics
    "AgentEvent",
    "AnalyticsConfig",
    "EventBuffer",
    "create_analytics",
    "detect_agent",
    # API Keys
    "ApiKeyConfig",
    "CreateApiKeyOptions",
    "CreateApiKeyResult",
    "ApiKeyValidationResult",
    "MemoryApiKeyStore",
    "ScopedApiKey",
    "create_api_key",
    "validate_api_key",
    "has_scope",
    # x402 Payments
    "X402Config",
    "X402RouteConfig",
    "PaymentRequirements",
    "resolve_price",
    "build_requirements",
    "build_payment_required",
    "encode_payment_required",
    "decode_payment_payload",
    "match_route",
    "handle_x402",
    # Agent Identity
    "AgentAuthzPolicy",
    "AgentIdentityAuditEvent",
    "AgentIdentityClaims",
    "AgentIdentityConfig",
    "AuthzContext",
    "AuthzResult",
    "SpiffeId",
    "build_audit_event",
    "decode_jwt_claims",
    "evaluate_authz",
    "extract_claims",
    "handle_optional_identity",
    "handle_require_identity",
    "is_spiffe_trusted",
    "parse_spiffe_id",
    "validate_claims",
    # Unified Discovery
    "DiscoveryFormats",
    "UnifiedAuthConfig",
    "UnifiedDiscoveryConfig",
    "UnifiedSkill",
    "generate_all_discovery",
    "generate_unified_agents_txt",
    "generate_unified_agent_card",
    "generate_unified_ai_manifest",
    "generate_unified_llms_full_txt",
    "generate_unified_llms_txt",
    # AG-UI
    "AG_UI_HEADERS",
    "AgUiEmitter",
    "AgUiEventType",
    "create_ag_ui_emitter",
    "encode_event",
    "encode_events",
    # OAuth2
    "OAuth2Config",
    "OAuth2MiddlewareConfig",
    "OAuth2TokenError",
    "PKCEPair",
    "TokenResponse",
    "TokenValidationResult",
    "build_authorization_url",
    "build_oauth2_metadata",
    "compute_code_challenge",
    "extract_bearer_token",
    "generate_code_verifier",
    "generate_pkce",
    "handle_oauth2",
    "validate_access_token",
    # Agent Meta
    "AgentMetaConfig",
    "transform_html",
]

__version__ = "0.1.0"
