"""agent-layer — Make web apps AI-agent-friendly."""

from agent_layer.errors import AgentError, format_error, not_found_error, rate_limit_error
from agent_layer.rate_limits import MemoryStore, build_rate_limit_headers, create_rate_limiter
from agent_layer.llms_txt import generate_llms_txt, generate_llms_full_txt
from agent_layer.discovery import generate_ai_manifest, generate_json_ld
from agent_layer.a2a import (
    A2AAgentCard,
    A2AConfig,
    A2ASkill,
    generate_agent_card,
    validate_agent_card,
)
from agent_layer.agent_identity import (
    AgentAuthzPolicyRuntime,
    AgentIdentityClaims,
    AgentIdentityConfig,
    AuthzContext,
    AuthzResult,
    IdentityResult,
    SpiffeId,
    TokenValidationError,
    build_audit_event,
    check_identity,
    decode_jwt_claims,
    evaluate_authz,
    extract_claims,
    extract_token_from_header,
    is_spiffe_trusted,
    parse_spiffe_id,
    validate_claims,
)
from agent_layer.analytics import (
    AgentEvent,
    AnalyticsConfig,
    AnalyticsInstance,
    EventBuffer,
    build_agent_event,
    create_analytics,
    detect_agent,
)
from agent_layer.mcp import (
    JsonRpcRequest,
    JsonRpcResponse,
    McpServerConfig,
    McpServerInfo,
    McpToolDefinition,
    build_input_schema,
    format_tool_name,
    generate_server_info,
    generate_tool_definitions,
    handle_json_rpc,
    parse_tool_name,
)
from agent_layer.x402 import (
    X402Config,
    X402RequestResult,
    X402RouteConfig,
    encode_settlement,
    process_x402_request,
)
from agent_layer.x402_client import (
    WalletSigner,
    extract_payment_requirements,
    is_payment_required,
    wrap_request_with_payment,
)
from agent_layer.unified_discovery import (
    UnifiedDiscoveryConfig,
    generate_agents_txt,
    generate_all_discovery,
    generate_unified_agent_card,
    generate_unified_ai_manifest,
    generate_unified_llms_full_txt,
    generate_unified_llms_txt,
)
from agent_layer.agents_txt import (
    AgentsTxtAuth,
    AgentsTxtConfig,
    AgentsTxtRateLimit,
    AgentsTxtRule,
    generate_agents_txt as generate_standalone_agents_txt,
    is_agent_allowed,
    parse_agents_txt,
)
from agent_layer.async_utils import run_async_in_sync

__all__ = [
    "AgentError",
    "format_error",
    "not_found_error",
    "rate_limit_error",
    "MemoryStore",
    "build_rate_limit_headers",
    "create_rate_limiter",
    "generate_llms_txt",
    "generate_llms_full_txt",
    "generate_ai_manifest",
    "generate_json_ld",
    "AgentEvent",
    "AnalyticsConfig",
    "AnalyticsInstance",
    "EventBuffer",
    "build_agent_event",
    "create_analytics",
    "detect_agent",
    "AgentAuthzPolicyRuntime",
    "AgentIdentityClaims",
    "AgentIdentityConfig",
    "AuthzContext",
    "AuthzResult",
    "IdentityResult",
    "SpiffeId",
    "TokenValidationError",
    "build_audit_event",
    "check_identity",
    "decode_jwt_claims",
    "evaluate_authz",
    "extract_claims",
    "extract_token_from_header",
    "is_spiffe_trusted",
    "parse_spiffe_id",
    "validate_claims",
    "A2AAgentCard",
    "A2AConfig",
    "A2ASkill",
    "generate_agent_card",
    "validate_agent_card",
    "JsonRpcRequest",
    "JsonRpcResponse",
    "McpServerConfig",
    "McpServerInfo",
    "McpToolDefinition",
    "build_input_schema",
    "format_tool_name",
    "generate_server_info",
    "generate_tool_definitions",
    "handle_json_rpc",
    "parse_tool_name",
    "X402Config",
    "X402RequestResult",
    "X402RouteConfig",
    "encode_settlement",
    "process_x402_request",
    "UnifiedDiscoveryConfig",
    "generate_agents_txt",
    "generate_all_discovery",
    "generate_unified_agent_card",
    "generate_unified_ai_manifest",
    "generate_unified_llms_full_txt",
    "generate_unified_llms_txt",
    "run_async_in_sync",
    "WalletSigner",
    "extract_payment_requirements",
    "is_payment_required",
    "wrap_request_with_payment",
    "AgentsTxtAuth",
    "AgentsTxtConfig",
    "AgentsTxtRateLimit",
    "AgentsTxtRule",
    "generate_standalone_agents_txt",
    "is_agent_allowed",
    "parse_agents_txt",
]
